# Generated by Django 4.1.7 on 2023-03-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="شرح")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("1", "انجام نشده"),
                            ("2", "در حال انجام"),
                            ("3", "انجام شده"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
                (
                    "do_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="آخرین بروز رسانی"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین بروز رسانی"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد کننده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تسک",
                "verbose_name_plural": "تسک ها",
            },
        ),
    ]
