# Generated by Django 4.1.7 on 2023-04-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_task_is_disabled_alter_task_creation_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_disabled",
        ),
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
    ]
